//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViajesUTP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pasajes
    {
        public int IdPasaje { get; set; }
        public int id_bus { get; set; }
        public int id_ubicacionDestino { get; set; }
        public int id_ubicacionOrigen { get; set; }
        public int NumAsientos { get; set; }
        public int id_usuario { get; set; }
        public Nullable<int> id_viaje { get; set; }
    
        public virtual Buses Buses { get; set; }
        public virtual Ubicacion Ubicacion { get; set; }
        public virtual Ubicacion Ubicacion1 { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Viajes Viajes { get; set; }
    }
}
